port: 4002
author: Mike Mai
title: Minimalist
subtitle: Minimal Design System
description: A design system built for and designed by Mike Mai.
ns: mnml
url: https://mikemai.net/design-system
s3: https://s3.amazonaws.com/mikemai
